//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEIL2VS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KEIL2VS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Enjoy VS Coding! 的本地化字符串。
        /// </summary>
        public static string enjoy_vs {
            get {
                return ResourceManager.GetString("enjoy_vs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Select Keil Vision4 Exe Path 的本地化字符串。
        /// </summary>
        public static string SELUV4PATH {
            get {
                return ResourceManager.GetString("SELUV4PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Visual Studio Project Creat Complete! 的本地化字符串。
        /// </summary>
        public static string sueecssTip1 {
            get {
                return ResourceManager.GetString("sueecssTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开VS工程(是) 的本地化字符串。
        /// </summary>
        public static string sueecssTip2 {
            get {
                return ResourceManager.GetString("sueecssTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹(否) 的本地化字符串。
        /// </summary>
        public static string sueecssTip3 {
            get {
                return ResourceManager.GetString("sueecssTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(取消) 的本地化字符串。
        /// </summary>
        public static string sueecssTip4 {
            get {
                return ResourceManager.GetString("sueecssTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置更新,请重新选择配置！ 的本地化字符串。
        /// </summary>
        public static string updateConfig {
            get {
                return ResourceManager.GetString("updateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the Visual Studio Project Path 的本地化字符串。
        /// </summary>
        public static string vsp_path {
            get {
                return ResourceManager.GetString("vsp_path", resourceCulture);
            }
        }
    }
}
